### ISSUE TITLE
Python 3 Install

### ISSUE THREAD

**Issue by xnmp** [billpmurphy/hask#21]
I can install `hask` with Python 2 with no issues, but in Python 3 I get the error:

```
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    import hask
  File "/home/user/Downloads/hask/hask/__init__.py", line 9, in <module>
    import Data.Char
ModuleNotFoundError: No module named 'Data'
```

This is presumably because relative imports are gone in Python 3. Is there any way to get it working regardless? I'm really keen to use this.

**Comment by ghost** [comment]
@xnmp This project seems pretty dead. I emailed the author, but he hasn't responded for a year.

**Comment by pya** [comment]
Coconut (https://github.com/evhub/coconut) seems to be a usable alternative.

**Comment by iamrecursion** [comment]
I can confirm that coconut is excellent. Well documented, usable and source compatible with Python 3.

**Comment by pya** [comment]
Yes, I worked my way through the tutorial. Feels like a working cross-over between Python and Haskell.

**Comment by ghost** [comment]
@xnmp @pya @iamrecursion Hey, it's been a pretty long time. I wanted to see if anyone's interested in joining me to create a Python 3 fix for `hask`. Coconut is usable, but it doesn't have the same level of tooling support and maturity as Python. Additionally, `hask` is far more functionally oriented, whereas Coconut simply happens to add functional syntax. Coconut doesn't have typeclasses, Haskell types, or decent type checking in a Hindley-Miller rather than default Python way.

I think it would be a very fun and useful endeavor.

**Comment by rzrn** [comment]
https://github.com/forked-from-1kasper/hask
I tried to port hask to Python 3. It works.
All tests pass, but not all of the code is covered by them.
We need to work even more, yes.
(no, this is not advertising)

**Comment by mvaled** [comment]
I have tried to communicate with the original author, but I've gotten no response.  I've recently published this on PyPI which supports Python 3 (up to whatever tests do test): https://pypi.org/project/hask3

I'm not probably taking over the project with the same goal of the original (that's why I changed the name to hask3), but I'm probably going to use some of it's features.

**Comment by james1293** [comment]
@forked-from-1kasper  and  @mvaled , what is the status of your forks? I may be interested in contributing.

**Comment by rzrn** [comment]
@james1293, if you want to contribute to my fork, then do it.

**Comment by mvaled** [comment]
My fork is https://github.com/mvaled/hask.  

But currently @med-merchise is doing most of the changes in https://gitlab.merchise.org/merchise/hask which I regularly push back to github.

When we starting exploring hask, we kept Python 2.7 support, but recently we decided to work only in Python 3.6+.  To make this decision less intrusive we also changed the package name to 'hask3' and made some initial releases in the PyPi: http://pypi.org/project/hask3

We may use hask3 in our project https://gitlab.merchise.org/merchise/xopgi.ql, which (will) implement an expression language.  hask3 may provide the *concrete* values in the language.  So far, we have done the basic typechecker.

**Comment by dmlerner** [comment]
Super cool. Is there active work going on, or a to do list? I'd be happy to contribute.

**Comment by mvaled** [comment]
@dmlerner I stopped doing any more changes on hask3.
